### ISSUE TITLE
BGEM3EmbeddingFunction no attribute 'ListViewType'  error on colab.

### ISSUE THREAD

**Issue by zc277584121** [milvus-io/milvus-model#32]
I'm trying to run following snippet:
```python
from pymilvus.model.hybrid import BGEM3EmbeddingFunction

ef = BGEM3EmbeddingFunction(use_fp16=False, device="cpu")
dense_dim = ef.dim["dense"]
print(dense_dim)
```
It raised an error:
```bash
/usr/local/lib/python3.10/dist-packages/pyarrow/_parquet.pyx in init pyarrow._parquet()

AttributeError: module 'pyarrow.lib' has no attribute 'ListViewType'
```
How should I fix it?

**Comment by wxywb** [comment]
According to https://github.com/huggingface/datasets/issues/6985
This error is raised due to  `datasets`'s dependency `pyarrow`(which is pre-installed on Colab) is not installed properly.
The quickest way to fix this is to run following snippet to force to reinstall `pyarrow` library and restart the session to make it available.
```bash
!pip install pyarrow==15.0.0
```
