### ISSUE TITLE
ImportError: cannot import name 'GEMMA2_ATTENTION_CLASSES' from 'transformers.models.gemma2.modeling_gemma2'

### ISSUE THREAD

**Issue by alexge233** [milvus-io/milvus-model#55]
Hi,

I'm just following the tutorial as seen here:
https://milvus.io/docs/embed-with-bgm-m3.md

The error I get is:
```
ImportError: cannot import name 'GEMMA2_ATTENTION_CLASSES' from 'transformers.models.gemma2.modeling_gemma2' (/venv/lib/python3.11/site-packages/transformers/models/gemma2/modeling_gemma2.py)
```
 
Package versions are:

```
milvus-lite               2.4.10
milvus-model              0.2.11
pymilvus                  2.5.0

sentence-transformers     3.3.1
transformers              4.47.0
```

Is this a version package issue?

**Comment by wxywb** [comment]
Yes, `transformers 4.47` has removed `GEMMA2_ATTENTION_CLASSES`, which has resulted in a broken dependency for FlagEmbedding. Please use `transformers 4.45` (tested). Also, run the code in the `__main__` function because FlagEmbedding includes some multi-processing logic recently, and it could cause errors if not run in the main function."
